### PR TITLE
v0.17.0.

### PR DESCRIPTION
**Pull request by tmeyer2115**
## Features
- For Entity Templates, you can now pick which Entity is used in the preview. (#311)
- Props can now have Developer-specified display names. When specified, these appear in the Prop Editor in place of the variable name. (#307)
- The Delete key now removes the currently selected Component. (#293)
- When an Entity Template's Stream Scope is edited, we re-generate the Test Data. (#317)

## Changes
- Repeaters are now deprecated. You cannot enable or disable Repeaters in the Studio UI. (#290)
- A Prop's Name now appears above its value selector. (#302)

## Bug Fixes
- Re-generation of `localData` now works properly if you have multiple, unsaved Entity Templates. (#304)
- Re-generation of `localData` no longer can cause a full page refresh. (#304)
- Studio now generates unique Stream Ids for the Entity Templates it creates. (#314)
- Assorted UI fixes. (#288, #298)

### CODE REVIEW

**Comment by oshi97** [comment]
#304 also fixes a bug where generating the test data can cause a full page refresh, I was thinking we'd include it in the notes since it was something Andrew asked about

**Comment by oshi97** [comment]
I also just merged in https://github.com/yext/studio/pull/317 if we want to include it?

**Comment by oshi97** [comment]
> > #304 also fixes a bug where generating the test data can cause a full page refresh, I was thinking we'd include it in the notes since it was something Andrew asked about
> 
> #304 is already called out in the release notes! It's the first bullet point under bug fixes.

I was thinking we could explicitly say it fixed this bug since it's conceptually separate from the bullet point we already have

**Comment by tmeyer2115** [comment]
> > > #304 also fixes a bug where generating the test data can cause a full page refresh, I was thinking we'd include it in the notes since it was something Andrew asked about
> > 
> > 
> > #304 is already called out in the release notes! It's the first bullet point under bug fixes.
> 
> I was thinking we could explicitly say it fixed this bug since it's conceptually separate from the bullet point we already have

Gotcha! I added a new bullet under fixes.

**Review by oshi97 — APPROVED** [review]

**Pull request merged**
